"""Evaluate the pipeline on the LROC real-illumination pairs.

Reads data/lroc/ (built by scripts/fetch_lroc_pairs.py) and writes
results/lroc/LROC.md and results/lroc/lroc_raw.json.

Two questions, scored separately:

1. **Accuracy** - ground-truth corner error on pairs that have truth. Truth is
   a known warp on top of a control network good to ~0.8 px (2 sigma), so
   errors below ~1 px are not resolvable here.
2. **The trust decision** - on positives, was a correct transform accepted and
   a wrong one refused? On negatives (different ground), was it refused?

    python scripts/evaluate_lroc.py
    python scripts/evaluate_lroc.py --presets seleno --matchers sift
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "backend"))

from seleno import matchers, pairs, registration, store       # noqa: E402
from seleno.experiments import build_options                  # noqa: E402

DATA = os.path.join(ROOT, "data", "lroc")
OUT = os.path.join(ROOT, "results", "lroc")
CORRECT_PX = 3.0            # a transform within this corner error counts as correct


def fmt(v, d=2):
    return "--" if v is None else ("%." + str(d) + "f") % v


def outcome(p: dict, status: str, err: float | None) -> str:
    """Classify one run against what the right answer was."""
    took = status in ("accepted", "warning")
    if p.get("negative"):
        return "false accept" if took else "correct refusal"
    good = err is not None and err <= CORRECT_PX
    if took:
        return "correct accept" if good else "false accept"
    return "missed (refused a solvable pair)" if good else "correct refusal"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--presets", default="baseline_verified,seleno")
    ap.add_argument("--matchers", default=None,
                    help="comma list; default = every available matcher")
    args = ap.parse_args()

    if not os.path.exists(os.path.join(DATA, "manifest.json")):
        print("data/lroc/manifest.json missing - run scripts/fetch_lroc_pairs.py first")
        return 1
    st = store.Store(DATA)
    presets = args.presets.split(",")
    mlist = (args.matchers.split(",") if args.matchers else
             [k for k, v in matchers.MATCHERS.items() if v["available"]
              and k != "sift_pyramid"])

    rows = []
    for p in st.pairs:
        spec = pairs.legacy_pair(st, p["id"])
        for preset in presets:
            for m in mlist:
                t0 = time.time()
                res = registration.run(spec, build_options(preset, spec, {"matcher": m}))
                met = res.metrics or {}
                gt = met.get("ground_truth") or {}
                err = gt.get("corner_error_px")
                rows.append({
                    "pair": p["id"], "preset": preset, "matcher": m,
                    "delta_sun_lon_deg": p.get("delta_sun_lon_deg"),
                    "negative": bool(p.get("negative")),
                    "status": res.status, "confidence": res.confidence,
                    "inliers": met.get("inliers"), "inlier_ratio": met.get("inlier_ratio"),
                    "heldout_px": (met.get("heldout") or {}).get("rmse_px"),
                    "gt_corner_px": err,
                    "outcome": outcome(p, res.status, err),
                    "reasons": res.reasons, "runtime_s": round(time.time() - t0, 2),
                })
                r = rows[-1]
                print("  %-34s %-18s %-6s %-9s err %-7s %s"
                      % (p["id"], preset, m, r["status"], fmt(err), r["outcome"]))

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "lroc_raw.json"), "w") as fh:
        json.dump(rows, fh, indent=1, default=str)

    L = ["# LROC real-illumination evaluation", "",
         "Generated by `scripts/evaluate_lroc.py` on %s from `data/lroc/`."
         % time.strftime("%Y-%m-%d %H:%M:%S"), "",
         "Pairs are windows of the LROC NAC controlled south-polar mosaics (1 m/px) "
         "under two different sub-solar-longitude bins. The illumination change is "
         "real; the reference is additionally warped by a known transform. Truth "
         "carries the control network's ~0.8 px (2 sigma) residual, so sub-pixel "
         "differences below that are not meaningful. A transform counts as "
         "correct at <= %.0f px corner error." % CORRECT_PX, "",
         "## 1. Every run", "",
         "| Pair | d-az | Preset | Matcher | Status | Inliers | Ratio | Held-out (px) "
         "| GT corner err (px) | Outcome |",
         "|---|--:|---|---|---|--:|--:|--:|--:|---|"]
    for r in rows:
        L.append("| `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            r["pair"], "neg" if r["negative"] else r["delta_sun_lon_deg"],
            r["preset"], r["matcher"], r["status"], r["inliers"],
            fmt(100 * r["inlier_ratio"], 1) + "%" if r["inlier_ratio"] is not None else "--",
            fmt(r["heldout_px"]), fmt(r["gt_corner_px"]), r["outcome"]))

    L += ["", "## 2. Summary by configuration", "",
          "Positives: pairs of the same ground. Negatives: different ground.", "",
          "| Preset | Matcher | Positives solved (err <= %.0f px) | Correct accepts "
          "| False accepts | Missed | Negatives refused | Median err, solved (px) |"
          % CORRECT_PX,
          "|---|---|--:|--:|--:|--:|--:|--:|"]
    for preset in presets:
        for m in mlist:
            rs = [r for r in rows if r["preset"] == preset and r["matcher"] == m]
            pos = [r for r in rs if not r["negative"]]
            neg = [r for r in rs if r["negative"]]
            solved = [r["gt_corner_px"] for r in pos
                      if r["gt_corner_px"] is not None and r["gt_corner_px"] <= CORRECT_PX]
            solved.sort()
            med = solved[len(solved) // 2] if solved else None
            cnt = lambda o, xs: sum(r["outcome"] == o for r in xs)  # noqa: E731
            L.append("| %s | %s | %d/%d | %d | %d | %d | %d/%d | %s |" % (
                preset, m, len(solved), len(pos), cnt("correct accept", pos),
                cnt("false accept", rs), cnt("missed (refused a solvable pair)", pos),
                cnt("correct refusal", neg), len(neg), fmt(med)))

    L += ["", "## 3. By Sun-direction change (all configurations pooled)", "",
          "| d-az (deg) | Runs | Solved | Correct accepts | False accepts |",
          "|--:|--:|--:|--:|--:|"]
    for d in sorted({r["delta_sun_lon_deg"] for r in rows if not r["negative"]}):
        rs = [r for r in rows if not r["negative"] and r["delta_sun_lon_deg"] == d]
        solved = sum(r["gt_corner_px"] is not None and r["gt_corner_px"] <= CORRECT_PX
                     for r in rs)
        L.append("| %s | %d | %d | %d | %d |" % (
            d, len(rs), solved, sum(r["outcome"] == "correct accept" for r in rs),
            sum(r["outcome"] == "false accept" for r in rs)))

    with open(os.path.join(OUT, "LROC.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("\nwrote %s" % os.path.relpath(os.path.join(OUT, "LROC.md"), ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
